# msapy Verification

The following notebook will attempt to verify the following for the instantiation of a single element object:
* nodes
* length
* transformation matrix
* local and global stiffness matrix
* degree of freedoms
* fixed-end forces

More complex checks:
* moment-released members
* self-weight
* complex geometric transformations
* beta angle
* beta angle + self_weight

In [1]:
import numpy as np
import msapy.firstorderelastic3D as mp
import pandas as pd
pd.set_option('precision', 3)

# Nodes

Verify node coordinate and DOF numbering works

In [2]:
# Create element object with the above attributes
node1 = mp.Node_3d1el(1,np.array([0,0,0]))
node2 = mp.Node_3d1el(2,np.array([80,80,0]))
end_node = np.array([node1,node2])

In [3]:
print(node1)

node number:  1
node coordinate: (0.00, 0.00, 0.00)
node DOF:  [1 2 3 4 5 6]

In [4]:
print(node2)

node number:  2
node coordinate: (80.00, 80.00, 0.00)
node DOF:  [ 7  8  9 10 11 12]

# Element Length, Stiffness, and Transformation

To verify that the nodes and element classes are working properly, create an element with the above two nodes and section property of W14x120.

From an existing working MATLAB implementation, the correct stiffness matrix (K) and transformation matrix (T) are provided in the image below.

<img src="resources\Verification 1 - 1.PNG" style="width: 400px">

Local Stiffness Matrix
<img src="resources\Verification 1 - 2.PNG" style="width: 600px">

Global Stiffness Matrix
<img src="resources\Verification 1 - 3.PNG" style="width: 600px">

Transformation Matrix
<img src="resources\Verification 1 - 4.PNG" style="width: 600px">

The length should be around 113.1 ft from simple triangle pythagorean theorem, and the degree of freedom should be an array from 1 to 12

In [5]:
A,Ayy,Azz=35.3, 8.55, 23.03
Iy,Iz,J=495, 1380, 9.37
E,v=29000,0.3
w=np.array([0,0,0])
weight = 0
release = np.array([0,0])
beta = 0
element1 = mp.Element_3d1el(1,'W14x120',end_node,A,Ayy,Azz,Iy,Iz,J,E,v,w,weight,release,beta)

In [6]:
print(element1)

Element #:  1
Element ID:  W14x120
i node: N1
j node: N2
DOF:  [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
Length: 113.137
A: 35.30
Ayy: 8.55
Azz: 23.03
Iy: 495.00
Iz: 1380.00
J: 9.37
E: 29000.00
v: 0.30
G: 11153.85
No solution available yet...

In [7]:
k_local_true=element1.k_local
pd.DataFrame(element1.k_local)

,0,1,2,3,4,5,6,7,8,9,10,11
0,9048.315,0.000,0.000,0.00,0.000,0.000e+00,-9048.315,0.000,0.000,0.00,0.000,0.000e+00
1,0.000,237.991,0.000,0.00,0.000,1.346e+04,0.000,-237.991,0.000,0.00,0.000,1.346e+04
2,0.000,0.000,113.030,0.00,-6393.923,0.000e+00,0.000,0.000,-113.030,0.00,-6393.923,0.000e+00
3,0.000,0.000,0.000,923.76,0.000,0.000e+00,0.000,0.000,0.000,-923.76,0.000,0.000e+00
4,0.000,0.000,-6393.923,0.00,488576.370,0.000e+00,0.000,0.000,6393.923,0.00,234813.424,0.000e+00
5,0.000,13462.819,0.000,0.00,0.000,1.115e+06,0.000,-13462.819,0.000,0.00,0.000,4.078e+05
6,-9048.315,0.000,0.000,0.00,0.000,0.000e+00,9048.315,0.000,0.000,0.00,0.000,0.000e+00
7,0.000,-237.991,0.000,0.00,0.000,-1.346e+04,0.000,237.991,0.000,0.00,0.000,-1.346e+04
8,0.000,0.000,-113.030,0.00,6393.923,0.000e+00,0.000,0.000,113.030,0.00,6393.923,0.000e+00
9,0.000,0.000,0.000,-923.76,0.000,0.000e+00,0.000,0.000,0.000,923.76,0.000,0.000e+00
10,0.000,0.000,-6393.923,0.00,234813.424,0.000e+00,0.000,0.000,6393.923,0.00,488576.370,0.000e+00
11,0.000,13462.819,0.000,0.00,0.000,4.078e+05,0.000,-13462.819,0.000,0.00,0.000,1.115e+06

In [8]:
k_global_true=element1.k_global
pd.DataFrame(element1.k_global)

,0,1,2,3,4,5,6,7,8,9,10,11
0,4643.153,4405.162,0.000,0.000,0.000,-9.520e+03,-4643.153,-4405.162,0.000,0.000,0.000,-9.520e+03
1,4405.162,4643.153,0.000,0.000,0.000,9.520e+03,-4405.162,-4643.153,0.000,0.000,0.000,9.520e+03
2,0.000,0.000,113.030,4521.186,-4521.186,0.000e+00,0.000,0.000,-113.030,4521.186,-4521.186,0.000e+00
3,0.000,0.000,4521.186,244750.065,-243826.305,0.000e+00,0.000,0.000,-4521.186,116944.832,-117868.592,0.000e+00
4,0.000,0.000,-4521.186,-243826.305,244750.065,0.000e+00,0.000,0.000,4521.186,-117868.592,116944.832,0.000e+00
5,-9519.650,9519.650,0.000,0.000,0.000,1.115e+06,9519.650,-9519.650,0.000,0.000,0.000,4.078e+05
6,-4643.153,-4405.162,0.000,0.000,0.000,9.520e+03,4643.153,4405.162,0.000,0.000,0.000,9.520e+03
7,-4405.162,-4643.153,0.000,0.000,0.000,-9.520e+03,4405.162,4643.153,0.000,0.000,0.000,-9.520e+03
8,0.000,0.000,-113.030,-4521.186,4521.186,0.000e+00,0.000,0.000,113.030,-4521.186,4521.186,0.000e+00
9,0.000,0.000,4521.186,116944.832,-117868.592,0.000e+00,0.000,0.000,-4521.186,244750.065,-243826.305,0.000e+00
10,0.000,0.000,-4521.186,-117868.592,116944.832,0.000e+00,0.000,0.000,4521.186,-243826.305,244750.065,0.000e+00
11,-9519.650,9519.650,0.000,0.000,0.000,4.078e+05,9519.650,-9519.650,0.000,0.000,0.000,1.115e+06

In [9]:
T_true = element1.T
pd.DataFrame(element1.T)

        0      1    2      3      4    5      6      7    8      9     10   11
0   0.707  0.707  0.0  0.000  0.000  0.0  0.000  0.000  0.0  0.000  0.000  0.0
1  -0.707  0.707  0.0  0.000  0.000  0.0  0.000  0.000  0.0  0.000  0.000  0.0
2   0.000  0.000  1.0  0.000  0.000  0.0  0.000  0.000  0.0  0.000  0.000  0.0
3   0.000  0.000  0.0  0.707  0.707  0.0  0.000  0.000  0.0  0.000  0.000  0.0
4   0.000  0.000  0.0 -0.707  0.707  0.0  0.000  0.000  0.0  0.000  0.000  0.0
5   0.000  0.000  0.0  0.000  0.000  1.0  0.000  0.000  0.0  0.000  0.000  0.0
6   0.000  0.000  0.0  0.000  0.000  0.0  0.707  0.707  0.0  0.000  0.000  0.0
7   0.000  0.000  0.0  0.000  0.000  0.0 -0.707  0.707  0.0  0.000  0.000  0.0
8   0.000  0.000  0.0  0.000  0.000  0.0  0.000  0.000  1.0  0.000  0.000  0.0
9   0.000  0.000  0.0  0.000  0.000  0.0  0.000  0.000  0.0  0.707  0.707  0.0
10  0.000  0.000  0.0  0.000  0.000  0.0  0.000  0.000  0.0 -0.707  0.707  0.0
11  0.000  0.000  0.0  0.000  0.000  0.0  0.000  0.000  0.0  0.000  0.000  1.0

# Fixed-end Forces

To check fixed-end forces, let's impose a unit load in all three local axes directions (i.e. {w} = {1,1,1}). Ideally, We should observe the following forces:

wa is causes axial force, wy causes z-bending, wz causes y-bending:
$$
w=[w_a,w_y,w_z]
$$

The fixed-end forces should be the following for no moment-release:  
{b_axial,b_yshear,b_zshear,b_torsion,b_ybending,b_zbending,
e_axial,e_yshear,e_zshear,e_torsion,e_ybending,e_zbending,}
$$
FEF = \begin{bmatrix}
           -w_aL/2 \\
           -w_yL/2 \\
           -w_zL/2 \\
           0 \\
           w_zL^2/12 \\
           -w_yL^2/12 \\
           -w_aL/2 \\
           -w_yL/2 \\
           -w_zL/2 \\
           0 \\
           -w_zL^2/12 \\
           w_yL^2/12 \\
         \end{bmatrix}
$$

For fixed-pinn condition:
* wa distributed 0.5-0.5 to each node
* shear distributed 5/8 to 3/8 where the fixed node take more load
* moment is 0 on the free-end, and wL<sup>2</sup>/8 on the fixed end

For pin-pin condition:
* wa, wy, and wz all distributed 0.5-0.5 to each node
* moment is 0 on both ends

In [15]:
w=[1,1,1]
element2 = mp.Element_3d1el(1,'W14x120',end_node,A,Ayy,Azz,Iy,Iz,J,E,v,w,weight,release,beta)

In [16]:
element2.FEF_local

array([  -56.56854249,   -56.56854249,   -56.56854249,     0.        ,
        1066.66666667, -1066.66666667,   -56.56854249,   -56.56854249,
         -56.56854249,     0.        , -1066.66666667,  1066.66666667])